# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Subtask.create([
  { :title => "", :description => "Sweep all areas with push broom or dry swiffers. Main areas - Foyer, Glass Room, Quiet Room, Meeting \r\nRoom 1, 2, 3 and 4, MPR", :finished => false, :task_id => 1, :created_at => "2014-01-08 04:22:02", :updated_at => "2014-01-08 04:22:02" },
  { :title => "", :description => "Go into EACH room and take out the full trash cans and reline ", :finished => false, :task_id => 2, :created_at => "2014-01-08 06:24:16", :updated_at => "2014-01-08 06:24:16" },
  { :title => "", :description => "Tie a small knot on the trash liner to ensure the trash bags are secure.", :finished => false, :task_id => 2, :created_at => "2014-01-08 06:24:38", :updated_at => "2014-01-08 06:24:38" },
  { :title => "", :description => "If the trashcan is dirty/wet/sticky, wash it out, dry and then line with trash bag.", :finished => false, :task_id => 2, :created_at => "2014-01-08 06:25:20", :updated_at => "2014-01-08 06:25:20" },
  { :title => "", :description => "Straighten tables and chairs. Make sure all chairs are neatly lined against the wall or pushed into the tables.", :finished => false, :task_id => 3, :created_at => "2014-01-08 06:27:04", :updated_at => "2014-01-08 06:27:04" },
  { :title => "", :description => "Tidy up, look for ANYTHING that does not belong and return it to the proper location", :finished => false, :task_id => 3, :created_at => "2014-01-08 06:27:30", :updated_at => "2014-01-08 06:27:30" },
  { :title => "", :description => "Wipe all the tables with a damp dishrag", :finished => false, :task_id => 3, :created_at => "2014-01-08 06:27:47", :updated_at => "2014-01-08 06:27:47" },
  { :title => "", :description => "Tidy up the metal racks", :finished => true, :task_id => 4, :created_at => "2014-01-08 06:29:26", :updated_at => "2014-01-08 07:10:53" },
  { :title => "", :description => "Tidy up the paper supplies. Make note of supplies that need to be restocked and let JOANNA KANG know.", :finished => true, :task_id => 4, :created_at => "2014-01-08 06:30:34", :updated_at => "2014-01-08 07:10:53" },
  { :title => "", :description => "Return ministry items to the correct metal rack  ", :finished => true, :task_id => 4, :created_at => "2014-01-08 06:31:44", :updated_at => "2014-01-08 07:10:53" },
  { :title => "", :description => "Straighten up ANYTHING that looks messy.", :finished => true, :task_id => 4, :created_at => "2014-01-08 06:32:03", :updated_at => "2014-01-08 07:10:53" },
  { :title => "", :description => "Wipe down and dry sink area/countertops.", :finished => false, :task_id => 5, :created_at => "2014-01-08 06:33:56", :updated_at => "2014-01-08 06:33:56" },
  { :title => "", :description => "Refill soap dispensers.", :finished => false, :task_id => 5, :created_at => "2014-01-08 06:34:25", :updated_at => "2014-01-08 06:34:25" },
  { :title => "", :description => "Refill paper towel dispensers/baskets, toilet paper, toilet seat covers. (Supplies are located in the General Supplies Room in MPR).", :finished => false, :task_id => 5, :created_at => "2014-01-08 06:34:48", :updated_at => "2014-01-08 06:34:48" },
  { :title => "", :description => "Empty trashcans, adding extra trash bags in bottom of trashcan", :finished => false, :task_id => 5, :created_at => "2014-01-08 06:35:12", :updated_at => "2014-01-08 06:35:12" },
  { :title => "", :description => "Sweep the floor", :finished => false, :task_id => 5, :created_at => "2014-01-08 06:35:47", :updated_at => "2014-01-08 06:35:47" },
  { :title => "", :description => "Sweep all areas with push broom or dry swiffers. Main areas - Foyer, Glass Room, Quiet Room, Meeting \r\nRoom 1, 2, 3 and 4, MPR", :finished => false, :task_id => 6, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Go into EACH room and take out the full trash cans and reline ", :finished => false, :task_id => 7, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Tie a small knot on the trash liner to ensure the trash bags are secure.", :finished => false, :task_id => 7, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "If the trashcan is dirty/wet/sticky, wash it out, dry and then line with trash bag.", :finished => false, :task_id => 7, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Straighten tables and chairs. Make sure all chairs are neatly lined against the wall or pushed into the tables.", :finished => false, :task_id => 8, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Tidy up, look for ANYTHING that does not belong and return it to the proper location", :finished => false, :task_id => 8, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Wipe all the tables with a damp dishrag", :finished => false, :task_id => 8, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Tidy up the metal racks", :finished => false, :task_id => 9, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Tidy up the paper supplies. Make note of supplies that need to be restocked and let JOANNA KANG know.", :finished => false, :task_id => 9, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Return ministry items to the correct metal rack  ", :finished => false, :task_id => 9, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Straighten up ANYTHING that looks messy.", :finished => false, :task_id => 9, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Wipe down and dry sink area/countertops.", :finished => false, :task_id => 10, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Refill soap dispensers.", :finished => false, :task_id => 10, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Refill paper towel dispensers/baskets, toilet paper, toilet seat covers. (Supplies are located in the General Supplies Room in MPR).", :finished => false, :task_id => 10, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Empty trashcans, adding extra trash bags in bottom of trashcan", :finished => false, :task_id => 10, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Sweep the floor", :finished => false, :task_id => 10, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" },
  { :title => "", :description => "Tidy up the metal racks", :finished => true, :task_id => 11, :created_at => "2014-01-08 07:31:49", :updated_at => "2014-01-08 07:33:50" },
  { :title => "", :description => "Return ministry items to the correct metal rack  ", :finished => true, :task_id => 11, :created_at => "2014-01-08 07:32:07", :updated_at => "2014-01-08 07:33:50" },
  { :title => "", :description => "Tidy up the paper supplies. Make note of supplies that need to be restocked and let JOANNA KANG know.", :finished => true, :task_id => 11, :created_at => "2014-01-08 07:32:24", :updated_at => "2014-01-08 07:33:50" },
  { :title => "", :description => "Straighten up ANYTHING that looks messy.", :finished => true, :task_id => 11, :created_at => "2014-01-08 07:32:55", :updated_at => "2014-01-08 07:33:50" }
])



Task.create([
  { :title => "Sweep", :lead_worker_id => "", :notes => "dry swiffers and push brooms can be found in supply room near bathrooms", :workers_that_finished_me => "", :task_session_id => 1, :task_template_id => nil, :created_at => "2014-01-08 04:09:44", :updated_at => "2014-01-08 07:34:06", :min_workers => 2, :max_workers => 3 },
  { :title => "Trash Maintenance", :lead_worker_id => "", :notes => "Trash bags can be found in the General Supplies Room", :workers_that_finished_me => "", :task_session_id => 1, :task_template_id => nil, :created_at => "2014-01-08 06:22:55", :updated_at => "2014-01-08 07:33:24", :min_workers => 1, :max_workers => 2 },
  { :title => "Tidy Up Rooms", :lead_worker_id => "", :notes => "MPR, Foyer, Quiet Room, Glass Room, Meeting Room 1, 2, 3 and 4 ", :workers_that_finished_me => "", :task_session_id => 1, :task_template_id => nil, :created_at => "2014-01-08 06:26:23", :updated_at => "2014-01-08 06:28:38", :min_workers => 3, :max_workers => 3 },
  { :title => "Bathrooms", :lead_worker_id => "", :notes => "Men’s, Women’s upstairs and downstairs ", :workers_that_finished_me => "", :task_session_id => 1, :task_template_id => nil, :created_at => "2014-01-08 06:33:00", :updated_at => "2014-01-08 06:57:58", :min_workers => 3, :max_workers => 4 },
  { :title => "Sweep", :lead_worker_id => "", :notes => "dry swiffers and push brooms can be found in supply room near bathrooms", :workers_that_finished_me => "", :task_session_id => nil, :task_template_id => 1, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00", :min_workers => 2, :max_workers => 3 },
  { :title => "Trash Maintenance", :lead_worker_id => "", :notes => "Trash bags can be found in the General Supplies Room", :workers_that_finished_me => "", :task_session_id => nil, :task_template_id => 1, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00", :min_workers => 1, :max_workers => 2 },
  { :title => "Tidy Up Rooms", :lead_worker_id => "", :notes => "MPR, Foyer, Quiet Room, Glass Room, Meeting Room 1, 2, 3 and 4 ", :workers_that_finished_me => "", :task_session_id => nil, :task_template_id => 1, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00", :min_workers => 3, :max_workers => 3 },
  { :title => "General Supplies Room ", :lead_worker_id => "", :notes => "", :workers_that_finished_me => "", :task_session_id => nil, :task_template_id => 1, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00", :min_workers => 1, :max_workers => 1 },
  { :title => "Bathrooms", :lead_worker_id => "", :notes => "Men’s, Women’s upstairs and downstairs ", :workers_that_finished_me => "", :task_session_id => nil, :task_template_id => 1, :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00", :min_workers => 3, :max_workers => 4 },
  { :title => "General Supplies Room ", :lead_worker_id => "", :notes => "", :workers_that_finished_me => "Yubo Diwu", :task_session_id => 1, :task_template_id => nil, :created_at => "2014-01-08 07:31:18", :updated_at => "2014-01-08 07:33:50", :min_workers => 1, :max_workers => 1 }
])



TaskSession.create([
  { :date => "2014-01-07 00:00:00", :title => "DL Daily Cleaning Checklist", :progress => 20, :admin => "Who does this stuff", :location => "Durant Loft", :created_at => "2014-01-08 04:09:23", :updated_at => "2014-01-08 07:33:50" }
])



TaskTemplate.create([
  { :date => "2014-01-07 00:00:00", :title => "DL Daily Cleaning Checklist", :created_by => "Who does this stuff", :location => "Durant Loft", :created_at => "2014-01-08 06:38:00", :updated_at => "2014-01-08 06:38:00" }
])

